server.port=8761

spring.application.name=eureka-server

# Eureka Server no se registra a si mismo
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

# Configuracion para entorno local academico
eureka.server.enable-self-preservation=false

# Logs
logging.level.com.netflix.eureka=INFO
logging.level.com.netflix.discovery=INFO
